name: Security Scan with Trivy

on:
  workflow_dispatch:

jobs:
  trivy-security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Crear SIEMPRE la carpeta para evitar "No files found" ---
      - name: Ensure results folder exists
        run: mkdir -p trivy-results

      # --- Instalar Trivy ---
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.2_Linux-64bit.deb
          sudo dpkg -i trivy_0.50.2_Linux-64bit.deb

      # --- Escaneo de la imagen ---
      - name: Run Trivy scan
        run: |
          IMAGE="ghcr.io/santyhernandez09/ecommerce-app:prod"
          trivy image --exit-code 0 --format json -o trivy-results/result.json "$IMAGE"
          trivy image --exit-code 0 --severity HIGH,CRITICAL --format table -o trivy-results/summary.txt "$IMAGE"

      # --- Renombrar artifact para evitar error "already exists" ---
      - name: Define unique artifact name
        id: artifact_name
        run: echo "NAME=trivy-results-${{ github.run_number }}-${{ github.run_attempt }}" >> $GITHUB_OUTPUT

      # --- Subir resultados ---
      - name: Upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact_name.outputs.NAME }}
          path: trivy-results/
          if-no-files-found: warn
