name: Security Scan Pipeline

on:
  workflow_dispatch:      # Se ejecuta manualmente con bot√≥n

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["api-gateway", "cloud-config", "favourite-service", "order-service", "payment-service", "product-service", "proxy-client", "service-discovery", "shipping-service", "user-service"]

    env:
      REGISTRY: ghcr.io
      REPO: ${{ github.repository }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t ${{ matrix.service }} ./services/${{ matrix.service }}

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@0.22.0
        with:
          image-ref: ${{ matrix.service }}
          format: "sarif"
          output: "trivy-results/${{ matrix.service }}.sarif"
          exit-code: "0"              # No falla el job aunque haya vulnerabilidades
          severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"

      - name: Upload SARIF artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: trivy-results/

  upload:
    needs: build-and-scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read

    strategy:
      matrix:
        file: [
          "api-gateway.sarif",
          "cloud-config.sarif",
          "favourite-service.sarif",
          "order-service.sarif",
          "payment-service.sarif",
          "product-service.sarif",
          "proxy-client.sarif",
          "service-discovery.sarif",
          "shipping-service.sarif",
          "user-service.sarif"
        ]

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: trivy-results

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-results/${{ matrix.file }}
